# Generated by Django 4.0 on 2022-01-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAPI', '0002_remove_projects_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
