# Generated by Django 4.0 on 2022-01-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAPI', '0003_projects_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_id',
        ),
    ]
