# Generated by Django 4.0 on 2022-03-31 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageAPI', '0004_remove_projects_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='assignee_user_id',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='author_user_id',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
    ]
